version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
      java: openjdk11
  build:
    commands:
      - chmod +x build.sh
      - ./build.sh int
      - ./build.sh deploy dev
#      - ./build.sh at